### ISSUE TITLE
Ionic

### ISSUE THREAD

**Issue by rebelholic** [Neo1975/ng-pdfviewer#1]
Why you don't never update this source again? Do you think it will compatible with Ionic Framework?

**Comment by Neo1975** [comment]
Hi,
Thanks for your attention.
I'm working in a new version but is not yet stable, I hope to update it
soon.
About Ionic I don't advice problems but to be honest I don't test it in
this framework, feel free to tell me is not.

Daniel
Il giorno dom 24 mag 2015 alle 07:54 rebelholic notifications@github.com
ha scritto:

**Comment by rebelholic** [comment]
Thanks for your answer I will looking your new update
